export const ADD_TODO = 'ADD_TODO'
export const CHANGE_TODO_STATE = 'CHANGE_TODO_STATE'
export const DELETE_TODO = 'DLELTE_TODO'
export const SET_DOING = 'SET_DOING'
export const SET_TIME = 'SET_TIME'
export const CHANGE_TIME_STATE = 'CHANGE_TIME_STATE'
